from __future__ import annotations

from typing import Any, Protocol

from sqlalchemy.orm import Session

from app.models import Transacao


class TransacaoRepositoryProtocol(Protocol):
    def get(self, db: Session, entity_id: Any) -> Transacao | None: ...
    def create(self, db: Session, entity: Transacao) -> Transacao: ...
    def delete(self, db: Session, entity: Transacao) -> None: ...
    def _save(self, db: Session, entity: Transacao) -> Transacao: ...
    def _save_many(self, db: Session, entities: list[Transacao]) -> list[Transacao]: ...
