"""initial

Revision ID: 9804a6a833db
Revises: 
Create Date: 2026-02-07 09:43:56.089466

"""
from alembic import op
import sqlalchemy as sa


revision = '9804a6a833db'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'TRANSFERENCIA', name='tipotransacao'), nullable=False),
    sa.Column('padrao', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('contas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('CARTEIRA', 'CONTA_CORRENTE', 'POUPANCA', 'INVESTIMENTO', 'OUTRO', name='tipoconta'), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contas_id'), 'contas', ['id'], unique=False)
    op.create_table('metas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_alvo', sa.Float(), nullable=False),
    sa.Column('valor_atual', sa.Float(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('concluida', sa.Boolean(), nullable=True),
    sa.Column('cor', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_id'), 'metas', ['id'], unique=False)
    op.create_table('config_cristao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('modo_ativo', sa.Boolean(), nullable=True),
    sa.Column('percentual_dizimo_padrao', sa.Float(), nullable=True),
    sa.Column('categoria_dizimo_id', sa.Integer(), nullable=True),
    sa.Column('igreja_nome', sa.String(length=200), nullable=True),
    sa.Column('igreja_endereco', sa.String(length=300), nullable=True),
    sa.Column('pastor_nome', sa.String(length=100), nullable=True),
    sa.Column('categoria_oferta_id', sa.Integer(), nullable=True),
    sa.Column('categoria_missoes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_dizimo_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['categoria_missoes_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['categoria_oferta_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_config_cristao_id'), 'config_cristao', ['id'], unique=False)
    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('valor_planejado', sa.Float(), nullable=False),
    sa.Column('valor_gasto', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orcamentos_id'), 'orcamentos', ['id'], unique=False)
    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', 'TRANSFERENCIA', name='tipotransacao'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('fixa', sa.Boolean(), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('confirmada', sa.Boolean(), nullable=True),
    sa.Column('transacao_uuid', sa.String(length=36), nullable=False),
    sa.Column('tem_dizimo', sa.Boolean(), nullable=True),
    sa.Column('percentual_dizimo', sa.Float(), nullable=True),
    sa.Column('transacao_dizimo_uuid', sa.String(length=36), nullable=True),
    sa.Column('e_dizimo', sa.Boolean(), nullable=True),
    sa.Column('entrada_origem_id', sa.Integer(), nullable=True),
    sa.Column('parcelado', sa.Boolean(), nullable=True),
    sa.Column('parcela_atual', sa.Integer(), nullable=True),
    sa.Column('total_parcelas', sa.Integer(), nullable=True),
    sa.Column('grupo_parcelamento_uuid', sa.String(length=36), nullable=True),
    sa.Column('e_emprestimo', sa.Boolean(), nullable=True),
    sa.Column('pessoa_emprestimo', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('meta_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['conta_id'], ['contas.id'], ),
    sa.ForeignKeyConstraint(['meta_id'], ['metas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transacoes_grupo_parcelamento_uuid'), 'transacoes', ['grupo_parcelamento_uuid'], unique=False)
    op.create_index(op.f('ix_transacoes_id'), 'transacoes', ['id'], unique=False)
    op.create_index(op.f('ix_transacoes_transacao_dizimo_uuid'), 'transacoes', ['transacao_dizimo_uuid'], unique=False)
    op.create_index(op.f('ix_transacoes_transacao_uuid'), 'transacoes', ['transacao_uuid'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transacoes_transacao_uuid'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_transacao_dizimo_uuid'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_id'), table_name='transacoes')
    op.drop_index(op.f('ix_transacoes_grupo_parcelamento_uuid'), table_name='transacoes')
    op.drop_table('transacoes')
    op.drop_index(op.f('ix_orcamentos_id'), table_name='orcamentos')
    op.drop_table('orcamentos')
    op.drop_index(op.f('ix_config_cristao_id'), table_name='config_cristao')
    op.drop_table('config_cristao')
    op.drop_index(op.f('ix_metas_id'), table_name='metas')
    op.drop_table('metas')
    op.drop_index(op.f('ix_contas_id'), table_name='contas')
    op.drop_table('contas')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
